% build_apr08_1d_report_panels
% Short note:
% 1. read saved report figures
% 2. make a few simple panel figures
% 3. save them in docs/figures

clear;
clc;

repo_root = fileparts(fileparts(mfilename('fullpath')));
fig_dir = fullfile(repo_root, 'docs', 'figures');

make_panel( ...
    { ...
    fullfile(fig_dir, 'apr08_1d_step1_sinking_speed_laws.png'), ...
    fullfile(fig_dir, 'apr08_1d_step1_travel_time_laws.png')}, ...
    1, 2, [120 120 1500 620], ...
    fullfile(fig_dir, 'apr08_1d_panel_step1.png'));

make_panel( ...
    { ...
    fullfile(fig_dir, 'apr08_1d_step3_diffusion_conservation.png'), ...
    fullfile(fig_dir, 'apr08_1d_step4_coagulation_conservation.png'), ...
    fullfile(fig_dir, 'apr08_1d_step5_fragmentation_conservation.png'), ...
    fullfile(fig_dir, 'apr08_1d_step7_sinking_conservation.png')}, ...
    2, 2, [120 120 1500 1180], ...
    fullfile(fig_dir, 'apr08_1d_panel_budget.png'));

make_panel( ...
    { ...
    fullfile(fig_dir, 'apr08_1d_step6_depth_profiles.png'), ...
    fullfile(fig_dir, 'apr08_1d_step6_depth_column_psd.png')}, ...
    1, 2, [120 120 1500 620], ...
    fullfile(fig_dir, 'apr08_1d_panel_step6.png'));

make_panel( ...
    { ...
    fullfile(fig_dir, 'apr08_1d_step7_sinking_scale_profile.png'), ...
    fullfile(fig_dir, 'apr08_1d_step7_sinking_final_column_psd.png')}, ...
    1, 2, [120 120 1500 620], ...
    fullfile(fig_dir, 'apr08_1d_panel_step7.png'));

make_panel( ...
    { ...
    fullfile(fig_dir, 'apr08_1d_step6_depth_profiles.png'), ...
    fullfile(fig_dir, 'apr08_1d_step6_depth_column_psd.png'), ...
    fullfile(fig_dir, 'apr08_1d_step7_sinking_scale_profile.png'), ...
    fullfile(fig_dir, 'apr08_1d_step7_sinking_final_column_psd.png')}, ...
    2, 2, [120 120 1500 1180], ...
    fullfile(fig_dir, 'apr08_1d_panel_depth.png'));

disp('Saved panel figures:');
disp(fullfile(fig_dir, 'apr08_1d_panel_step1.png'));
disp(fullfile(fig_dir, 'apr08_1d_panel_budget.png'));
disp(fullfile(fig_dir, 'apr08_1d_panel_step6.png'));
disp(fullfile(fig_dir, 'apr08_1d_panel_step7.png'));
disp(fullfile(fig_dir, 'apr08_1d_panel_depth.png'));

function make_panel(img_paths, nrow, ncol, fig_pos, out_path)
fig = figure('Color', 'w', 'Position', fig_pos);
tl = tiledlayout(fig, nrow, ncol, 'TileSpacing', 'compact', 'Padding', 'compact');

for i = 1:numel(img_paths)
    ax = nexttile(tl, i);
    img = imread(img_paths{i});
    image(ax, img);
    axis(ax, 'image');
    axis(ax, 'off');
end

exportgraphics(fig, out_path, 'Resolution', 200);
close(fig);
end
